# Generated by Django 6.0.1 on 2026-03-01 19:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmas_sales', '0004_cliente_created_at_cliente_identidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contable', models.DateField(db_index=True)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_documento', models.CharField(db_index=True, max_length=50)),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('cliente_identidad', models.CharField(blank=True, default='', max_length=50)),
                ('cliente_rtn', models.CharField(blank=True, default='', max_length=50)),
                ('subtotal_gravado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_exento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('MIXTO', 'Mixto')], default='CONTADO', max_length=10)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=10)),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libros_venta', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='libro_venta', to='farmas_sales.venta')),
            ],
            options={
                'db_table': 'libro_ventas',
                'indexes': [models.Index(fields=['fecha_contable'], name='libro_venta_fecha_c_30d7b8_idx'), models.Index(fields=['numero_documento'], name='libro_venta_numero__406d0e_idx')],
            },
        ),
    ]
