# Generated by Django 6.0.1 on 2026-03-05 00:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmas_accounting', '0001_initial'),
        ('farmas_purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('proveedor_nombre', models.CharField(max_length=255)),
                ('proveedor_rtn', models.CharField(blank=True, default='', max_length=30)),
                ('factura_proveedor', models.CharField(blank=True, default='', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('isv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=10)),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='libro_compra', to='farmas_purchases.compra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libros_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'libro_compras',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha'], name='libro_compr_fecha_3da521_idx')],
            },
        ),
    ]
