# Generated by Django 6.0.1 on 2026-02-12 01:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmas_inventory', '0002_producto_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
