# Generated by Django 6.0.1 on 2026-02-18 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmas_sales', '0003_alter_detalleventa_cantidad_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='identidad',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
