# Generated by Django 6.0.1 on 2026-02-03 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmas_inventory', '0001_initial'),
        ('farmas_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_usados', to='farmas_sales.detalleventa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='farmas_inventory.lote')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_usados', to='farmas_sales.venta')),
            ],
        ),
    ]
