# Generated by Django 6.0.1 on 2026-02-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmas_sales', '0002_ventalote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
