# Generated by Django 6.0.1 on 2026-02-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmas_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
